### ISSUE TITLE
Address Error

### ISSUE THREAD

**Issue by PasakornSky** [m24927605/BCH_Node_InsightAPI#1]
I got this error, maybe it's caused from new CashAddress, Thanks.

error: uncaught exception: Error: Non-base58 character
    at Object.decode (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51:37)
    at Function.Base58.decode (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/base58.js:48:26)
    at Function.Base58Check.decode (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/base58check.js:45:31)
    at Function.Address._transformString (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/address.js:279:35)
    at Address._classifyArguments (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/address.js:107:20)
    at new Address (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/address.js:73:19)
    at Object.Address (/usr/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/lib/address.js:51:12)
    at TxController.transformOutput (/usr/lib/node_modules/bitcore/node_modules/insight-api/lib/transactions.js:153:27)
    at Array.map (<anonymous>)
    at TxController.transformTransaction (/usr/lib/node_modules/bitcore/node_modules/insight-api/lib/transactions.js:77:42)

**Comment by m24927605** [comment]
I find a new way to build a restful api server for bitcoin cash and it also
support cashaddress.
This is my build steps.

https://github.com/m24927605/bitcore-node-v8-node.git



PasakornSky <notifications@github.com> 於 2018年6月19日 週二 下午8:32寫道：
